domogik config file changed for req/rep/pub/sub, broker(req/rep) forwarder(pub/sub) worker(req/rep) (as)syncclient(req/rep) are reading the config file now, added forwarder to init script, moved some files to make it more logical

diff --git a/src/domogik/examples/init/domogik b/src/domogik/examples/init/domogik
--- a/src/domogik/examples/init/domogik
+++ b/src/domogik/examples/init/domogik
@@ -36,6 +36,7 @@ NAME=dmg_manager
 C_XPLHUB=xPL_Hub
 PYTHON_XPLHUB=dmg_hub
 MQ_BROKER=dmg_broker
+MQ_FORWARDER=dmg_forwarder
 DIETIME=2
 STARTTIME=5
 #PIDDIR=$(grep "^pid_dir_path" /etc/domogik/domogik.cfg | cut -d " " -f 3)
@@ -68,6 +69,13 @@ function start_mq {
     /bin/su - ${DOMOGIK_USER} -c "$(which ${MQ_BROKER}) >/dev/null"
     if [ $? -gt 0 ]; then
         echo " An error occured during 0MQ broker startup."
+        exit 1
+    fi
+    echo " Done."
+    echo -n " * Starting 0MQ forwarder ..."
+    /bin/su - ${DOMOGIK_USER} -c "$(which ${MQ_FORWARDER}) >/dev/null"
+    if [ $? -gt 0 ]; then
+        echo " An error occured during 0MQ forwarder startup."
         exit 1
     fi
     echo " Done."
@@ -165,6 +173,15 @@ function status_mq {
     else
         echo " * ${MQ_BROKER} is not running"
     fi
+    set +e
+    RUNNING=$(/usr/bin/pgrep -c ${MQ_FORWARDER})
+    set -e
+    if [ ! -z ${RUNNING} ] && [ ${RUNNING} -gt 0 ] ; then
+        echo " * ${MQ_FORWARDER} is running"
+    else
+        echo " * ${MQ_FORWARDER} is not running"
+    fi
+
 }
 
 function status_xpl {
@@ -214,6 +231,14 @@ function stop_mq {
         kill -9 $pid 2>/dev/null 1>&2
     done
     echo " Done."
+    echo -n " * Stopping 0MQ forwarder..."
+    for pid in `ps ax | grep "${MQ_FORWARDER}" | grep -v grep | awk '{print $1}'`; do
+        kill -15 $pid 2>/dev/null 1>&2
+        sleep ${DIETIME}
+        kill -9 $pid 2>/dev/null 1>&2
+    done
+    echo " Done."
+
 }
 
 function stop_xpl {
