Domoweb : comment ui reference from sample files. Need to be cleaned (see #TODO : DEL# tags)

diff --git a/src/domogik/examples/init/domogik b/src/domogik/examples/init/domogik
--- a/src/domogik/examples/init/domogik
+++ b/src/domogik/examples/init/domogik
@@ -40,25 +40,25 @@ if [ $UID != 0 ];then
     exit 1;
 fi
 
-function start_django {
-    echo -n " * Starting Django..."
-    USER_HOME=$(grep $DOMOGIK_USER /etc/passwd | cut -d":" -f6)
-    DJANGO_SERVER_IP=$(grep "^django_server_ip" ${USER_HOME}/.domogik/domogik.cfg | cut -d " " -f 3)
-    if [ -z ${DJANGO_SERVER_IP} ] ; then
-        DJANGO_SERVER_IP=127.0.0.1
-    fi
-    DJANGO_SERVER_PORT=$(grep "^django_server_port" ${USER_HOME}/.domogik/domogik.cfg | cut -d " " -f 3)
-    if [ -z ${DJANGO_SERVER_PORT} ] ; then
-        DJANGO_SERVER_PORT=8000
-    fi
-    /bin/su - ${DOMOGIK_USER} -c "dmg_django runserver ${DJANGO_SERVER_IP}:${DJANGO_SERVER_PORT}>/var/log/domogik/django.log 2>&1 &"
-    if [ $? -gt 0 ]; then
-        echo " An error occured during Django startup."
-        exit 1
-    else
-        echo " Done."
-    fi
-}
+#TODO : DEL#function start_django {
+#TODO : DEL#    echo -n " * Starting Django..."
+#TODO : DEL#    USER_HOME=$(grep $DOMOGIK_USER /etc/passwd | cut -d":" -f6)
+#TODO : DEL#    DJANGO_SERVER_IP=$(grep "^django_server_ip" ${USER_HOME}/.domogik/domogik.cfg | cut -d " " -f 3)
+#TODO : DEL#    if [ -z ${DJANGO_SERVER_IP} ] ; then
+#TODO : DEL#        DJANGO_SERVER_IP=127.0.0.1
+#TODO : DEL#    fi
+#TODO : DEL#    DJANGO_SERVER_PORT=$(grep "^django_server_port" ${USER_HOME}/.domogik/domogik.cfg | cut -d " " -f 3)
+#TODO : DEL#    if [ -z ${DJANGO_SERVER_PORT} ] ; then
+#TODO : DEL#        DJANGO_SERVER_PORT=8000
+#TODO : DEL#    fi
+#TODO : DEL#    /bin/su - ${DOMOGIK_USER} -c "dmg_django runserver ${DJANGO_SERVER_IP}:${DJANGO_SERVER_PORT}>/var/log/domogik/django.log 2>&1 &"
+#TODO : DEL#    if [ $? -gt 0 ]; then
+#TODO : DEL#        echo " An error occured during Django startup."
+#TODO : DEL#        exit 1
+#TODO : DEL#    else
+#TODO : DEL#        echo " Done."
+#TODO : DEL#    fi
+#TODO : DEL#}
 
 function start_xpl {
     if [ -z "$(which xPL_Hub)" ];then
@@ -90,13 +90,13 @@ function start_manager {
     rm -f /tmp/dmg-manager-state
 }
 
-function stop_django {
-    echo -n " * Stopping Django..."
-    for pid in `ps ax | grep "dmg_django runserver" | grep -v grep | awk '{print $1}'`; do
-        kill -15 $pid 2>/dev/null 1>&2
-    done
-    echo " Done."
-}
+#TODO : DEL#function stop_django {
+#TODO : DEL#    echo -n " * Stopping Django..."
+#TODO : DEL#    for pid in `ps ax | grep "dmg_django runserver" | grep -v grep | awk '{print $1}'`; do
+#TODO : DEL#        kill -15 $pid 2>/dev/null 1>&2
+#TODO : DEL#    done
+#TODO : DEL#    echo " Done."
+#TODO : DEL#}
 
 function stop_xpl {
     echo -n " * Stopping XPL..."
@@ -145,12 +145,12 @@ case "$1" in
     if [ $# -eq 1 ];then
         start_xpl
         start_manager
-        start_django
+        #TODO : DEL#start_django
     else
         case "$2" in
-            django)
-            start_django
-            ;;
+            #TODO : DEL#django)
+            #TODO : DEL#start_django
+            #TODO : DEL#;;
             xpl)
             start_xpl
             ;;
@@ -163,15 +163,15 @@ case "$1" in
     ;;
     stop)
     if [ $# -eq 1 ];then
-        stop_django
+        #TODO : DEL#stop_django
         stop_plugins
         stop_xpl
         stop_manager
     else
         case "$2" in
-            django)
-            stop_django
-            ;;
+            #TODO : DEL#django)
+            #TODO : DEL#stop_django
+            #TODO : DEL#;;
             xpl)
             stop_xpl
             ;;
@@ -191,6 +191,7 @@ case "$1" in
     $0 start $2
     ;;
     *)
-    echo "usage: $0 {start|stop|restart} [(django|xpl|manager|plugins)]"
+    #TODO : DEL#echo "usage: $0 {start|stop|restart} [(django|xpl|manager|plugins)]"
+    echo "usage: $0 {start|stop|restart} [(xpl|manager|plugins)]"
 esac
 exit 0
